{% set name = "psy-view" %}
{% set version = "0.1.0" %}
{% set sha256 = "85a3a08dca1dfc95594308bb5d185aa8cc66cdc704981a267eec41a36cb16e5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - psy-view = psy_view:main

  skip: true  # [py == 36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('psyplot-gui', max_pin='x.x') }}
    - {{ pin_compatible('psy-maps', max_pin='x.x') }}
    - netcdf4

test:
  imports:
    - psy_view
    - psy_view.ds_widget

  commands:
    - psy-view --help

app:
  entry: psy-view
  icon: logo.png
  summary: Quick-view for netCDF files
  type: desk

about:
  home: https://github.com/psyplot/psy-view
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: ncview-like interface for psyplot

  description: |
    This package provides a graphical user interface to quickly visualize the
    contents of a netCDF file
  doc_url: http://psyplot.readthedocs.io/projects/psy-view
  dev_url: https://github.com/psyplot/psy-view

extra:
  recipe-maintainers:
    - Chilipp
