{% set name = "psy-view" %}
{% set version = "0.2.0" %}
{% set sha256 = "25d57c8fc784a662c89dae5672b22dc11b137ebefb39e7b4d8df358bb185e58e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  entry_points:
    - psy-view = psy_view:main

  skip: true  # [py == 36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('psyplot-gui', max_pin='x.x') }}
    - {{ pin_compatible('psy-maps', max_pin='x.x') }}
    - netcdf4

test:
  imports:
    - psy_view
    - psy_view.ds_widget

  commands:
    - psy-view --help

app:
  entry: psy-view
  icon: logo.png
  summary: Quick-view for netCDF files
  type: desk

about:
  home: https://github.com/psyplot/psy-view
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: ncview-like interface for psyplot

  description: |
    This package provides a graphical user interface to quickly visualize the
    contents of a netCDF file
  doc_url: http://psyplot.github.io/psy-view
  dev_url: https://github.com/psyplot/psy-view

extra:
  recipe-maintainers:
    - Chilipp
